export const traductionValues = {
  id: 'ID',
  title: 'Título',
  style: 'Estilo',
  structure: 'Estructura',
  pastors: 'Pastores',
  services: 'Servicios',
  mission: 'Misión',
  facebooklink: 'Enlace de Facebook',
  instagramlink: 'Enlace de Instagram',
  whatsapplink: 'Enlace de WhatsApp',
  maplink: 'Enlace del Mapa',
  youtubelink: 'Enlace de YouTube',
  preachlink: 'Enlace de la predica',
  donationlink: 'Enlace de Donación',
  animations: 'Animaciones',
  location: 'Ubicación',
  description: 'Descripción',
  aboutus: 'Sobre Nosotros',
  color: 'Color',
  language: 'Idioma',
  date: 'Fecha',
  eventid: 'ID del Evento',
  imageurl: 'URL de la Imagen',
  activityid: 'ID de la Actividad',
  text: 'Texto',
  username: 'Nombre de Usuario',
  churchname: 'Nombre de la Iglesia',
  birthday: 'Fecha de nacimiento',
  civilstatus: 'Estado civil',
  name: 'Nombre',
  body: 'Cuerpo',
  img: 'Imagen',
  membername: 'Miembro',
  pastorname: 'Pastor',
  member2name: 'Miembro',
  pastor2Name: 'Pastor',
  expeditiondate: 'Fecha de expedición',
  logo: 'Logo',
  model: 'Modelo',
  brand: 'Marca',
  price: 'Precio',
  serie: 'Serie',
  amount: 'Cantidad',
  obsertvations: 'Observaciones',
  bill: 'Factura',
  cellphone: 'Teléfono',
  baptized: 'Bautizado',
  email: 'Correo electrónico',
  genre: 'Genero',
  positionid: 'Cargo',
  perm_members: 'Permiso de miembros',
  perm_websites: 'Permiso de pagina web',
  perm_finances: 'Permiso de finanzas',
  perm_certificates: 'Permiso de certificados',
  perm_inventory: 'Permiso de inventario',
  perm_blog: 'Permiso de blog',
  perm_classes: 'Permiso de clases',
  classid: 'Clase',
  notes: 'Notas',
  joindate: 'Fecha de membresía',
};

export const getTraduction = (value: string | number) => {
  if (typeof value === 'number') value = value.toString();
  const lowerValue = value.toLowerCase();

  return traductionValues[lowerValue] || value;
};
